# Generated by Django 3.2 on 2023-01-28 16:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('status', models.IntegerField(default=1)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('price', models.FloatField(default=0)),
                ('status', models.IntegerField(default=1)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=30, null=True)),
                ('customer_number', models.CharField(blank=True, max_length=11, null=True)),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('seriel_no', models.IntegerField(blank=True, default=0, null=True)),
                ('cnic', models.CharField(blank=True, default='nill', max_length=15, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('ladies', models.IntegerField(blank=True, default=0, null=True)),
                ('gents', models.IntegerField(blank=True, default=0, null=True)),
                ('sub_total', models.FloatField(blank=True, default=0, null=True)),
                ('grand_total', models.FloatField(blank=True, default=0, null=True)),
                ('tax_amount', models.FloatField(blank=True, default=0, null=True)),
                ('tax', models.FloatField(blank=True, default=0, null=True)),
                ('perhead_charges', models.FloatField(blank=True, default=0, null=True)),
                ('hall', models.FloatField(blank=True, default=0, null=True)),
                ('tendered_amount', models.FloatField(blank=True, default=0, null=True)),
                ('amount_change', models.FloatField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('extra_charges', models.IntegerField(blank=True, default=0, null=True)),
                ('sub', models.IntegerField(blank=True, default=0, null=True)),
                ('cash_received', models.IntegerField(blank=True, default=0, null=True)),
                ('event_time', models.CharField(blank=True, max_length=6, null=True)),
                ('customer_address', models.CharField(blank=True, default='Nill', max_length=200, null=True)),
                ('balance_due', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='salesItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('qty', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posApp.products')),
                ('sale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posApp.sales')),
            ],
        ),
    ]
